name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test_docker_image:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mras:latest .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name mras-container --rm mras:latest

      - name: Stop Docker container
        run: docker stop mras-container

      - name: Tag Docker image
        run: docker tag mras:latest ${{ secrets.DOCKER_USERNAME }}/mras:latest

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mras:latest

      - name: Remove Docker image
        run: docker rmi mras
